# Generated by Django 5.0.3 on 2024-03-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ежедневно'), (2, 'раз в два дня'), (3, 'раз в три дня'), (4, 'раз в четыре дня'), (5, 'раз в пять дней'), (6, 'раз в шесть дней'), (7, 'раз в семь дней')], default='1', max_length=20, verbose_name='периодичность привычки'),
        ),
    ]
