# Generated by Django 5.0.3 on 2024-03-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_habit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='useful',
            field=models.BooleanField(default=False, verbose_name='признак полезная привычка'),
        ),
    ]
